[package]
name = "gitflow"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
lazy_static = "1.4.0"
serde_json = "1.0.117"
termion = "4.0.2"
